name: example
description: Example app using synchronize_cache.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  synchronize_cache:
    path: ../packages/synchronize_cache
  synchronize_cache_rest:
    path: ../packages/synchronize_cache_rest
  drift: ^2.27.0
  sqlite3_flutter_libs: ^0.5.31
  path: ^1.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  drift_dev: ^2.27.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  test: ^1.25.15

